###Далее "объект" - json-объект
################### /api/history ###################
### Headers:
### Result-Count: возвращенное количество объектов
### Total-Count: общее количество обьектов соответствующее переданному предикату

### Возвращены до 1000 объектов
GET localhost:8080/api/history
### Пагинация. Возвращены 1001 обьект, 4 "страница"
GET localhost:8080/api/history?size=1001&page=4
### Фильтрация
GET localhost:8080/api/history?id=1&from=1565654400&to=1565827200
###
GET localhost:8080/api/history?id=4&objectId=2
### Возвращены все обьекты с time > 1613189196
GET localhost:8080/api/history?from=1613189196
### Возвращены все обьекты с time < 1613189196
GET localhost:8080/api/history?to=1613189196
### Возвращены все обьекты с time = 1613189196
GET localhost:8080/api/history?time=1613189196
### Возвращены все обьекты с time != 1613189196
GET localhost:8080/api/history?time=ne(1613189196)
### Возвращены все обьекты с time > 1613189196
GET localhost:8080/api/history?time=gt(1613189196)
### Возвращены все обьекты с time < 1613189196
GET localhost:8080/api/history?time=lt(1613189196)
### Возвращены все обьекты с time <= 1613189196
GET localhost:8080/api/history?time=lte(1613189196)
###
### Возвращены все обьекты с measure.time < 1613189196 || !(measure.time < 1613189196)
GET localhost:8080/api/history?time=lt(1613189196)&time=not(lt(1613189196))

################### /api/latest ###################
### Возвращены текущие (последние на данных момент) значения всех датчиков для заданного объекта.
GET localhost:8080/api/latest?id=3
################### /api/avg ###################
### Возвращены средние из текущих значений датчиков для каждого объекта
GET localhost:8080/api/avg
################### /api/save ###################
### сохранить измерения датчиков,
### передаваемые как список json структур
### (объект, датчик, время в секундах, значение).
POST localhost:8080/api/save
Content-Type: application/json

[
  {
    "objectId": 1,
    "sensorId": 2,
    "time": 1,
    "value": 9.4
  },
  {
    "objectId": 1,
    "sensorId": 2,
    "time": 2,
    "value": 14.2
  },
  {
    "objectId": 2,
    "sensorId": 4,
    "time": 3,
    "value": 14.2
  }
]

### swagger-json
GET localhost:8080/v2/api-docs
###